### PR TITLE
feat: clickable message avatars [AR-1465]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1465" title="AR-1465" target="_blank">TaskAR-1465</a>  Navigate to other user’s profile from the conversation with them
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

User needs to be able to navigate to self or other profile by clicking on user's avatar on conversation screen.

### Solutions

Implemented clickable avatar navigating to the self or other profile, added some small visual updates to the other profile screen.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Open conversation and click on the avatar that's next to the message.

### Attachments (Optional)

https://user-images.githubusercontent.com/30429749/180040337-120dde3e-7aaf-4c40-979f-cf5e1b64c1eb.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-784/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3937001)(3937001)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3937001)(3937001)-dev-release.apk)

**Review by MohamadJaara — APPROVED** [review]
lgtm 🚀

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-784/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-784/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3943907)(3943907)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3943907)(3943907)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-784/5/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-784/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3944256)(3944256)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3944256)(3944256)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-784/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3951170)(3951170)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3951170)(3951170)-dev-release.apk)

**Pull request merged**
