### PR TITLE
test: configure di for authenticated tests

### PR DESCRIPTION
**Pull request by yamilmedina**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Currently, we weren't able to run tests that required to have a valid session beforehand, ie: remove devices screen or conversations screen. This PR adds a Hilt configuration replacement for tests, but only for `SessionModule`.

- The `TestModule` (that we can expand later in case of needed) replaces the `SessionModule` 
- This replacement consists, in case there is no session, we do a manual login and session persistence, otherwise we return the current session

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [X] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3021610)(3021610)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3021610)(3021610)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3029226)(3029226)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3029226)(3029226)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3029319)(3029319)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3029319)(3029319)-dev-release.apk)

**Review by dogaguclu — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3035985)(3035985)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3035985)(3035985)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3040893)(3040893)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3040893)(3040893)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3044904)(3044904)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3044904)(3044904)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3045497)(3045497)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3045497)(3045497)-dev-release.apk)

**Review by ohassine — APPROVED** [review]
👌

**Comment by AndroidBob** [comment]
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3045658)(3045658)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3045658)(3045658)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/11/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3046833)(3046833)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3046833)(3046833)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-479/12/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3047135)(3047135)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3047135)(3047135)-dev-release.apk)

**Pull request merged**
