### PR TITLE
chore: update translation strings via Crowdin

### PR DESCRIPTION
**Pull request by gongracr**

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-919/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4305491)(4305491)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4305491)(4305491)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-919/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4308077)(4308077)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4308077)(4308077)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-919/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4313759)(4313759)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4313759)(4313759)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
lgmt  ! 🚀 🤖

**Pull request merged**
