### PR TITLE
fix: update inaccurate strings

### PR DESCRIPTION
**Pull request by gongracr**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues
Updated a series of strings upon request from Astrid as it seems the synchronisation failed somehow in Crowdin for her.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-932/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-932/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4349352)(4349352)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4349352)(4349352)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
🚀

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-932/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4349556)(4349556)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4349556)(4349556)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-932/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4349916)(4349916)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4349916)(4349916)-dev-release.apk)

**Pull request merged**
