### PR TITLE
fix: mute/unmute visuals displayed with delay for self user

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

mute/unmute visuals displayed with delay for self user.

### Causes (Optional)

We were using values returned by AVS

### Solutions

use local values for current user and AVS values for other participants 

Needs releases with:

- [ ] GitHub link to other pull request

#### How to Test

Make a call and try to mute or unmute yourself
visuals state should change immediately without any delay

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-739/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3797885)(3797885)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3797885)(3797885)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-739/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3804269)(3804269)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3804269)(3804269)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-739/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3804833)(3804833)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3804833)(3804833)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-739/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3805637)(3805637)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3805637)(3805637)-dev-release.apk)

**Review by trOnk12 — APPROVED** [review]
add a comment and we are a good to go 💯

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-739/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3813161)(3813161)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3813161)(3813161)-dev-release.apk)

**Pull request merged**
