### PR TITLE
delete me: intentionall rollback

### PR DESCRIPTION
**Pull request by tmspzz**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/6/) **failed**.

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/7/) **failed**.

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/8/) **failed**.

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/9/) **failed**.

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/12/) **failed**.

**Comment by AndroidBob** [comment]
Build [14](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/14/) **failed**.

**Comment by AndroidBob** [comment]
Build [15](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/15/) **failed**.

**Comment by AndroidBob** [comment]
Build [16](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/16/) **failed**.

**Comment by AndroidBob** [comment]
Build [24](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/24/) **failed**.

**Comment by AndroidBob** [comment]
Build [25](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/25/) **failed**.

**Comment by AndroidBob** [comment]
Build [27](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/27/) **failed**.

**Comment by AndroidBob** [comment]
Build [29](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/29/) **failed**.

**Comment by AndroidBob** [comment]
Build [30](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/30/) **failed**.

**Comment by AndroidBob** [comment]
Build [32](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/32/) **failed**.

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/8/) **failed**.

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/12/) **failed**.

**Comment by AndroidBob** [comment]
Build [26](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/26/) **failed**.

**Comment by AndroidBob** [comment]
Build [27](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/27/) **failed**.

**Comment by AndroidBob** [comment]
Build [28](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/28/) **failed**.

**Comment by AndroidBob** [comment]
Build [30](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/30/) **failed**.

**Comment by AndroidBob** [comment]
Build [33](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/33/) **failed**.

**Comment by AndroidBob** [comment]
Build [34](https://10.10.124.134/job/wire-android-reloaded/job/PR-811/34/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4015931)(4015931)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4015931)(4015931)-dev-release.apk)

**Comment by yamilmedina** [comment]
I think we can close safely this PR, since now we have running this action for every PR 🙌

**Pull request closed without merging**
