### PR TITLE
feat: add decryption failure messages [AR-1657]

### PR DESCRIPTION
**Pull request by gongracr**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1657" title="AR-1657" target="_blank">TaskAR-1657</a>  TODO: Display a failed message when failing to decrypt messages
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When decrypting regular messages operation failed, we didn't have any way to inform or give some visual feedback to the user. This PR fixes this according to [ticket](https://wearezeta.atlassian.net/browse/AR-1657)

### Solutions

Created some extra `MessageDecryptionFailure` compose class to display an error message to the user when any message decryption went wrong. The support link is also localised so that it takes you to the correct support website if you are in the German version

### Dependencies (Optional)

This needs to be merged after its [Kalium counterpart](https://github.com/wireapp/kalium/pull/746) has been merged too

Needs releases with:

https://github.com/wireapp/kalium/pull/746

- [x] GitHub link to other pull request

#### How to Test

Since testing this manually would be quite complicated, I added a screen recording of what would look like if a message failed to decrypt with a dummy easter egg text.

### Attachments (Optional)

https://user-images.githubusercontent.com/2468164/182394983-8b4e1fbc-861b-4e69-9969-f01e19d4a4cf.mov

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-819/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-819/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4048392)(4048392)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4048392)(4048392)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
gogogo! good work compa!

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-819/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4049256)(4049256)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4049256)(4049256)-dev-release.apk)

**Pull request merged**
