### PR TITLE
fix: too frequent conversation list updates

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Conversation list updates were being done too frequently, especially when first launching the app and because of that the whole list was being rearranged every time.

### Causes (Optional)

When fixing one issue with 1-1 conversations with deleted user, we created this one, because until now empty item was emitted at the beginning for each conversation and because of that every actual update with proper data (for every conversation independently) was emitting the whole list again.

### Solutions

Updated kalium reference and handled passing storage failure through the flow (we will need to handle failures properly on screens).

Needs releases with:

- https://github.com/wireapp/kalium/pull/726

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Open the app and see if the list of conversations flickers (changes the order and size multiple times).

#### With flickering:

https://user-images.githubusercontent.com/30429749/181587582-7bd49432-d2df-46ec-841a-d6a4c34463c7.mp4

&nbsp;
#### Without flickering:

https://user-images.githubusercontent.com/30429749/181587730-86a78809-ea17-48e3-bc70-e66769e0e1f3.mp4

----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-808/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-808/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4005683)(4005683)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4005683)(4005683)-dev-release.apk)

**Review by ohassine — COMMENTED** [review]
Nice fix 👌 looks much better 🔥
Just one thing, I don't see the list updated based on recent activities in the video you shared.

**Comment by saleniuk** [comment]
> Nice fix 👌 looks much better 🔥 Just one thing, I don't see the list updated based on recent activities in the video you shared.

@ohassine I actually recorded the moment when there was no update 😅 
Here it is with the update (I got a message in the "test groupp" in the meantime so it jumped to the top of the list):

https://user-images.githubusercontent.com/30429749/181730273-30dcb9d7-f197-4b6c-abc4-6cda1bcf4f9c.mp4

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-808/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4012053)(4012053)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4012053)(4012053)-dev-release.apk)

**Review by ohassine — APPROVED** [review]
Well done 😎

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-808/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4014476)(4014476)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4014476)(4014476)-dev-release.apk)

**Pull request merged**
