### PR TITLE
refactor: unify QualifedId mapping in one place

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Description
This PR aims to apply the changes made on this PR on kalium side for refactoring qualifiedId mapping
 [refactor: Unify QualifedId mapping in one place ](https://github.com/wireapp/kalium/pull/719) 

### Dependencies (Optional)

Needs to be merged with 
 [refactor: Unify QualifedId mapping in one place ](https://github.com/wireapp/kalium/pull/719) 

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4005757)(4005757)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4005757)(4005757)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4006166)(4006166)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4006166)(4006166)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4006352)(4006352)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4006352)(4006352)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4011233)(4011233)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4011233)(4011233)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/9/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4011590)(4011590)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4011590)(4011590)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4011871)(4011871)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4011871)(4011871)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/12/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4012517)(4012517)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4012517)(4012517)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [15](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/15/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4014021)(4014021)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4014021)(4014021)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [17](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/17/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4037280)(4037280)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4037280)(4037280)-dev-release.apk)

**Review by gongracr — APPROVED** [review]
LGTM 🍬

**Comment by AndroidBob** [comment]
Build [19](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/19/) **failed**.

**Comment by AndroidBob** [comment]
Build [20](https://10.10.124.134/job/wire-android-reloaded/job/PR-805/20/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4048157)(4048157)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4048157)(4048157)-dev-release.apk)

**Pull request merged**
