### PR TITLE
test: Add personal account tests

### PR DESCRIPTION
**Pull request by dogaguclu**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3444780)(3444780)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3444780)(3444780)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3451192)(3451192)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3451192)(3451192)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3494590)(3494590)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3494590)(3494590)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3494698)(3494698)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3494698)(3494698)-dev-release.apk)

**Comment by dogaguclu** [comment]
when I run the test locally they all pass,
Screenshot 2022-05-30 at 17 14 02
Screenshot 2022-05-30 at 17 15 45

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3495785)(3495785)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3495785)(3495785)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3502532)(3502532)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3502532)(3502532)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3503897)(3503897)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3503897)(3503897)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/11/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3511840)(3511840)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3511840)(3511840)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/12/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3512105)(3512105)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3512105)(3512105)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [17](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/17/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3512683)(3512683)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3512683)(3512683)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [19](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/19/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3519107)(3519107)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3519107)(3519107)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [20](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/20/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3519838)(3519838)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3519838)(3519838)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [21](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/21/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3521513)(3521513)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3521513)(3521513)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [22](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/22/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3521975)(3521975)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3521975)(3521975)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [23](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/23/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3528952)(3528952)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3528952)(3528952)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [24](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/24/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3530771)(3530771)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3530771)(3530771)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [27](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/27/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3564713)(3564713)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3564713)(3564713)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
good work! nice to have these espresso tests back in place =)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3935628)(3935628)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3935628)(3935628)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-610/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3936018)(3936018)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3936018)(3936018)-dev-release.apk)

**Pull request closed without merging**
