### PR TITLE
fix: system messages design review changes [AR-1143]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1143" title="AR-1143" target="_blank">StoryAR-1143</a>   Conversation setting messages (system) 
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

System messages still needed some polishing in order to pass the design review. There were some [comments](https://wearezeta.atlassian.net/browse/AR-1143?focusedCommentId=102200) from Wolfgang needed to be addressed.

----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-679/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3649596)(3649596)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3649596)(3649596)-dev-release.apk)

**Review by vitorhugods — APPROVED** [review]
Perhaps we could add tests to this mapper to make sure we don't have regressions.

Other than that, nicely done.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-679/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3651252)(3651252)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3651252)(3651252)-dev-release.apk)

**Comment by saleniuk** [comment]
There are already some tests for both mappers. 🙂

**Pull request merged**
