### PR TITLE
fix: disable RTL

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

RTL is not supported in the app, and there is no translation

### Solutions

disable RTL until we officially support it 

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-840/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4107690)(4107690)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4107690)(4107690)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
👨‍🍳

**Comment by ohassine** [comment]
why do we have to disable RTL ?

**Comment by ohassine** [comment]
Except translation, I think nothing extra todo to support RTL, the app should be adapted automatically

**Comment by MohamadJaara** [comment]
> Except translation, I think nothing extra todo to support RTL, the app should be adapted automatically

There are some stuffs stuff to-do, e.g., some arrows need to be flipped

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-840/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4116708)(4116708)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4116708)(4116708)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-840/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4158265)(4158265)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4158265)(4158265)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-840/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4161524)(4161524)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4161524)(4161524)-dev-release.apk)

**Pull request merged**
