### PR TITLE
chore: Notifications improve (AR-1059)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1059" title="AR-1059" target="_blank">StoryAR-1059</a>  Receive notification for incoming call and accept/decline it
  </td></table>
  <br />
 

Needed for [Task-1059](https://wearezeta.atlassian.net/browse/AR-1059)

# What's new in this PR?

Small refactoring in Notifications needed for IncomingCall notifications

## Can be merged after https://github.com/wireapp/wire-android-reloaded/pull/627

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-628/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3469690)(3469690)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3469690)(3469690)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-628/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3493115)(3493115)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3493115)(3493115)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-628/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3512940)(3512940)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3512940)(3512940)-dev-release.apk)

**Review by gongracr — APPROVED** [review]
LGTM! 🍰 ☕

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-628/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3519383)(3519383)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3519383)(3519383)-dev-release.apk)

**Pull request merged**
