### PR TITLE
chore: add basic config for coverage

### PR DESCRIPTION
**Pull request by yamilmedina**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] contains a reference JIRA issue number like `SQPIT-764`
  
- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

As I was looking at the configuration on `quality.gradle.kts` we already had configured JaCoCo, also [CodeCov](https://app.codecov.io/gh/wireapp/wire-android-reloaded/commits?page=1) was also configured for the project, so I just did minor config changes, that enabled the coverage report to be displayed on every PR.

I had to enable that our unit-tests action, also were triggered on `develop` branch, so we can have a point of comparison

#### How to Test

You can go to CodeCov app and see the reports uploaded, otherwise you can also check the CodeCov commenting the PR:

- https://app.codecov.io/gh/wireapp/wire-android-reloaded/commits?page=1
- https://github.com/wireapp/wire-android-reloaded/pull/510#issuecomment-1099108405

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [X] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]
🚀

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-510/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3098866)(3098866)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3098866)(3098866)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-510/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3131175)(3131175)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3131175)(3131175)-dev-release.apk)

**Review by ohassine — APPROVED** [review]
👌👌

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-510/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3142391)(3142391)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3142391)(3142391)-dev-release.apk)

**Pull request merged**
