### PR TITLE
chore: adjust calling button dimensions

### PR DESCRIPTION
**Pull request by alexandreferris**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Due to upgrading Material version to v3, icons dimensions were changed (due to not having both width/height specified)

### Solutions

Add both width AND height to calling icons

### Images
| OLD Design | New Design |
| ------------- | ------------- |
| old_init  | new_init  |
| old_incoming  | new_incoming  |

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-612/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3451589)(3451589)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3451589)(3451589)-dev-release.apk)

**Review by vitorhugods — APPROVED** [review]
I couldn't help but notice that the `Microphone` button doesn't align with the screen center:

tá torto alí

So this might bring some discussion on how to handle it with the designers.

And... Kalium reference was updated, but I guess that's alright. No breaking changes, the app builds correctly.
Code-wise, everything looks good :)

**Review by ohassine — APPROVED** [review]
🚀👌

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-612/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3451835)(3451835)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3451835)(3451835)-dev-release.apk)

**Pull request merged**
