### PR TITLE
feat: add conversation options UI and display group name [AR-1721]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1721" title="AR-1721" target="_blank">StoryAR-1721</a>  Show items in group conversation details page
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

User needs to be able to view all relevant information about group conversation available under ‘Options’ tab in conversation details page.

### Solutions

Implemented UI element to show all types of options items. Added getting and displaying conversation name as a first options item.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Open group conversation details by clicking on title dropdown on conversation screen.

### Attachments (Optional)

image

image

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-692/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3692957)(3692957)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3692957)(3692957)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-692/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3694349)(3694349)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3694349)(3694349)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-692/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3700381)(3700381)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3700381)(3700381)-dev-release.apk)

**Review by MohamadJaara — APPROVED** [review]
Great work 🚀

**Pull request merged**
