### PR TITLE
feat: add login SSO UI [AR-1159]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1159" title="AR-1159" target="_blank">SubtaskAR-1159</a>  sso UI
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We need to have SSO login, in order to add it we need to make changes to the login screen.

### Solutions

- created WireTabRow with unified styling
- added tabs to login screen
- created LoginSSOScreen with input field

### Testing

Added `LoginSSOViewModelTest`.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Just like on the video below. 😄 

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

https://user-images.githubusercontent.com/30429749/162436388-4946ebda-e240-4e44-9f31-19790db61a92.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-494/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3045521)(3045521)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3045521)(3045521)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-494/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3045749)(3045749)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3045749)(3045749)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-494/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3045946)(3045946)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3045946)(3045946)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-494/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3046331)(3046331)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3046331)(3046331)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-494/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3070792)(3070792)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3070792)(3070792)-dev-release.apk)

**Review by ohassine — APPROVED** [review]
👌

**Pull request merged**
