### PR TITLE
chore: update CoreLogic initialisation after refactoring

### PR DESCRIPTION
**Pull request by typfel**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

https://github.com/wireapp/kalium/pull/370 changed they way we initialise CoreLogic in a breaking way.

### Solutions

Update root directory which we pass to CoreLogic.

### Dependencies (Optional)

Needs releases with:

- [x] https://github.com/wireapp/kalium/pull/370

#### How to Test

App still runs.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-491/1/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by alexandreferris** [comment]
> Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-491/1/) **failed**.

Both tests failed for the same issue 🤔  

```
e: /home/runner/work/wire-android-reloaded/wire-android-reloaded/app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt: (51, 13): Cannot find a parameter with this name: rootPath

e: /home/runner/work/wire-android-reloaded/wire-android-reloaded/app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt: (51, 24): Unresolved reference: proteusPath
e: /home/runner/work/wire-android-reloaded/wire-android-reloaded/app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt: (53, 9): No value passed for parameter 'rootProteusDirectoryPath'
```

**Comment by typfel** [comment]
> > Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-491/1/) **failed**.
> 
> Both tests failed for the same issue 🤔
> 
> ```
> e: /home/runner/work/wire-android-reloaded/wire-android-reloaded/app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt: (51, 13): Cannot find a parameter with this name: rootPath
> 
> e: /home/runner/work/wire-android-reloaded/wire-android-reloaded/app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt: (51, 24): Unresolved reference: proteusPath
> e: /home/runner/work/wire-android-reloaded/wire-android-reloaded/app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt: (53, 9): No value passed for parameter 'rootProteusDirectoryPath'
> ```

Yeah Kalium is not updated. It's a git submodule?

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-491/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-491/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3044595)(3044595)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3044595)(3044595)-dev-release.apk)

**Review by alexandreferris — APPROVED** [review]

**Pull request merged**
