### PR TITLE
feat: federation resilient users (AR-2097)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2097" title="AR-2097" target="_blank">SubtaskAR-2097</a>  Add Placeholder to members of conversations that could not be fetched
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

In case we are not able to get info for federated users, we need to still be able to log in or interact with the app.
To handle users fetching, we are doing the following with this PR:

- Adding placeholders, when users are unavailable to fetch
- Placeholders added to, conversation list, conversation details, group conversation participants.

### Causes (Optional)

The app is able to load in a federated environment when these users are not able to fetch before, we were failing on sync

Needs releases with:

https://github.com/wireapp/kalium/pull/795

- [x] GitHub link to other pull request

### Attachments (Optional)

https://user-images.githubusercontent.com/5806454/185087383-c5011c91-cb1a-446b-8c69-d9ac5c51bc2b.mov

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-858/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-858/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4168237)(4168237)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4168237)(4168237)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-858/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4169090)(4169090)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4169090)(4169090)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-858/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4175696)(4175696)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4175696)(4175696)-dev-release.apk)

**Review by alexandreferris — APPROVED** [review]
👌🏻

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-858/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4176078)(4176078)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4176078)(4176078)-dev-release.apk)

**Review by gongracr — APPROVED** [review]
GJ 👏 🍓

**Pull request merged**
