### PR TITLE
chore: bump core dependencies

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Some dependencies have released newer and more stable versions. 

### Solutions

Update to catch them.
- Kotlin to 1.6.21
- Compose to 1.2.0-beta
- Accompanist to a newer version too.

#### Material3 Was buggy

It seems now `Scaffold` [will pass the internal margin in the lambda](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.0.0-alpha10) to draw internal content.

Looks like this:

----

So, in order to fix bugs mentioned above, we need to call `Modifier.padding(it)`.

Something like:

```kotlin
Scaffold(topBar = { WireCenterAlignedTopAppBar() }) { internalPadding ->
    MyContent(modifier = Modifier.padding(internalPadding))
}
```

I've applied this on all `Scaffold` in the app and after giving it a run, it seems to be all working fine.

Fixed:

Now everything seems correct.

#### How to Test

Just open the app and have fun playing around with it.

----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by vitorhugods** [comment]
On Material3:
It seems now `Scaffold` [will pass the internal margin in the lambda](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.0.0-alpha10) to draw internal content.

So, in order to fix bugs mentioned above, we need to call `Modifier.padding(it)`.

Something like:

```kotlin
Scaffold(topBar = { WireCenterAlignedTopAppBar() }) { internalPadding ->
    MyContent(modifier = Modifier.padding(internalPadding))
}
```

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-588/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3385732)(3385732)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3385732)(3385732)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-588/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3389658)(3389658)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3389658)(3389658)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-588/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3391318)(3391318)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3391318)(3391318)-dev-release.apk)

**Review by saleniuk — APPROVED** [review]

**Pull request merged**
