### PR TITLE
chore: tune coverage settings

### PR DESCRIPTION
**Pull request by yamilmedina**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  
- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

This PR configures the coverage settings, so we are now ignoring code that can not be unit tested.
Also, as this will theoretically will improve the coverage, we are not enforcing a hard rule on min code coverage %

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [X] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-560/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3262367)(3262367)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3262367)(3262367)-dev-release.apk)

**Review by gongracr — COMMENTED** [review]
Does this mean that we are not encouraging other devs to write tests for composable items? 🙄

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-560/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3268576)(3268576)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3268576)(3268576)-dev-release.apk)

**Comment by yamilmedina** [comment]
> Does this mean that we are not encouraging other devs to write tests for composable items? 🙄

I think in some way, yes, since this composable items are in the scope of Espresso tests because we need a way to interact with the UI most of the time, or we need some Android SDK components.

But, we can discuss it on the Collective given this is just an action item from the retro :D

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-560/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3277975)(3277975)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3277975)(3277975)-dev-release.apk)

**Review by ohassine — APPROVED** [review]
🚀🚀

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-560/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3311526)(3311526)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3311526)(3311526)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-560/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3311728)(3311728)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3311728)(3311728)-dev-release.apk)

**Pull request merged**
