### PR TITLE
feat: show the remaining membership qualifiers (AR-1182)

### PR DESCRIPTION
**Pull request by trOnk12**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1182" title="AR-1182" target="_blank">StoryAR-1182</a>  Display user metadata (membership qualifier) in 1:1 and group conversation view
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

- as for now Kalium has additional type on the OtherUser model which is UserType, we need to consume this type and map it to the membership qualifier where we want to display MembershipQualifierLabel

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-708/4/) **failed**.

**Review by vitorhugods — APPROVED** [review]
🚀✨

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-708/6/) **failed**.

**Review by gongracr — APPROVED** [review]
LGTM, although maybe it would be good to add some `ContactMapper` unit tests if possible

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-708/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3711653)(3711653)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3711653)(3711653)-dev-release.apk)

**Pull request merged**
