### PR TITLE
fix: duplicated texts on system messages [AR-1991]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1991" title="AR-1991" target="_blank">BugAR-1991</a>  System message for missed call shows "called" twice
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When we missed a call, the system message in the conversation shows the word “called” twice. The same for "person left the conversation".

### Solutions

The code fixed to get the resource only once and not pass the whole text again as a parameter. Additionally, adjusted the positioning of icons on system messages.

#### How to Test

Miss a call or make another member to leave a conversation and look at the system messages informing about both situations.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-758/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3865422)(3865422)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3865422)(3865422)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-758/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3866492)(3866492)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3866492)(3866492)-dev-release.apk)

**Review by gongracr — APPROVED** [review]
I don't see anything odd in this PR, altough it would be great if next time these ones could come with some screenshots so that we have a visual hint and/or to check right away everything looks great. GJ removing those duplicates 🤖 !

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-758/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3867058)(3867058)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3867058)(3867058)-dev-release.apk)

**Pull request merged**
