### PR TITLE
fix: change member role bottom sheet style [AR-1603]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1603" title="AR-1603" target="_blank">StoryAR-1603</a>  Promote group convo members to admins (and demote them)
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

The bottom sheet to change member's role does not match the designs and looks different than the usual bottom sheet component (font weight is bold, no check icon for the selected item).

### Solutions

Updated default item composable to be more universal, moved "check" icon inside to be added automatically, adjusted bottom sheet header and updated the way of setting it (can be visible or gone).

#### How to Test

Conversation details (being an admin) -> member details -> edit role button.

### Attachments (Optional)

Screenshot_20220817_173324

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-865/1/) **failed**.

**Review by MohamadJaara — APPROVED** [review]
LGTM 🚀

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-865/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4178501)(4178501)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4178501)(4178501)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-865/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4178628)(4178628)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4178628)(4178628)-dev-release.apk)

**Pull request merged**
