### PR TITLE
feat: Receive Availability status from others

### PR DESCRIPTION
**Pull request by borichellow**
[Task-2090](https://wearezeta.atlassian.net/browse/AR-2090)

# What's new in this PR?

Added handling Availability status changing from the other users, saving it into DB and displaying

## Needs releases with:
[Kalium PR ](https://github.com/wireapp/kalium/pull/715)

### Attachments (Optional)

photo_5406766958810086996_y

Wire 2022-07-26 at 15_48 copy

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-801/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-801/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3994841)(3994841)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3994841)(3994841)-dev-release.apk)

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-801/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4012781)(4012781)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4012781)(4012781)-dev-release.apk)

**Review by gongracr — APPROVED** [review]
Great job, one step closer to have fully functional User Availability Status 🗽

**Comment by vitorhugods** [comment]
rebuild

**Comment by vitorhugods** [comment]
rebuild

**Comment by tmspzz** [comment]
Our CI was down, validated build with https://app.bitrise.io/app/c030c37f8cda058c

**Pull request merged**
