### PR TITLE
fix: reinitiate email input from saved state

### PR DESCRIPTION
**Pull request by dmkasperski**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?
https://wearezeta.atlassian.net/browse/AR-1598

### Issues

When Android 12 user tries to create personal account and enters email and navigating to webview to see TOU, after returning to the app from webview text field is cleared
### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions
I wasn't able to reproduce the issue and others also tried to reproduce it without a luck

I checked the code responsible for that and I don't see any changes after creating the bug ticket that could solve the problem. 

The only improvement/potential fix I see there is to save email and in case of reinitiating ViewModel with a saved state, view model constructor creates a default TextFieldValue with an empty string so that's the only place I found that can cause the problem, but the ViewModel is created much before so it's not destroyed when a user opens webview, so theoretically this change changes nothing but on the other hand, email was cleared when it shouldn't be. 

also as no one can reproduce the problem maybe it was some weird one time issue, when maybe device memory was full or something and it's an edge case, maybe not worth solving and wait to happen it again 

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test
Happens only on Android 12

Steps:
1. Before Login
2. Tap on Create a personal account
3. Continue
4. input a valid email
5. Continue
6. Tap ToC
7. Terms page opens
8. Device back button

Result:
The email field is cleared

Expected:
The email field should not be cleared

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-637/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3510987)(3510987)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3510987)(3510987)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-637/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3519934)(3519934)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3519934)(3519934)-dev-release.apk)

**Review by MohammedMokresh — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-637/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3527974)(3527974)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3527974)(3527974)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-637/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3561520)(3561520)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3561520)(3561520)-dev-release.apk)

**Review by yamilmedina — COMMENTED** [review]
Great first PR @dmkasperski ! 👏  I see the possible solution presented here, but I'm hesitant to solve something that could not be reproduced, so I think it's a good idea that more people can take a look and see if they are good too.

**Comment by dmkasperski** [comment]
@yamilmedina totally agrees and as mentioned in the description, how bad it sounds but I wouldn't merge this unless this appears again because I wasn't able to test if this actually helped because I couldn't reproduce the problem in first place

**Review by saleniuk — APPROVED** [review]
@dmkasperski I probably reproduced it with "don't keep activities" developer flag on. I think it mimics the situation where the screen is destroyed due to low memory for instance and then recreated when reopened. I can confirm that this solution works for the situation where the screen is restored. 😉

**Review by yamilmedina — APPROVED** [review]
Since we were able to reproduce, let's goo, great work @dmkasperski

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-637/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3580215)(3580215)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3580215)(3580215)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-637/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3580422)(3580422)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3580422)(3580422)-dev-release.apk)

**Pull request merged**
