### PR TITLE
feat: add participants to a group conversation (AR-1016)

### PR DESCRIPTION
**Pull request by trOnk12**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1016" title="AR-1016" target="_blank">StoryAR-1016</a>  Add Participants to Group Conversations
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

- We were not able to add participants to a group

### Solutions

- I created a SearchPeopleViewModel() as a abstract ViewModel which has 3 methods that are going to be overriden to get the search results : 

```
    abstract suspend fun getAllUsersUseCase(): SearchResult

    abstract suspend fun searchKnownUsersUseCase(searchTerm: String): SearchResult

    abstract suspend fun searchPublicUsersUseCase(searchTerm: String): SearchResult
```

- SearchPeopleRouter now depends on this SearchPeopleViewModel it also exposes onPeoplePicked lambda which allows us to trigger an action when the "New Group: button is clicked

- Added AddMembersToConversationViewModel extending SearchPeopleViewModel()
   
- Create AddConversationParticipants NavigationItem that allows us to navigate to SearchPeopleRouter() :
 inside the  content = {  }  of NavigationItem i pass the AddMembersToConversationViewModel() that delegates the search, also  onPeoplePicked lambda makes a call to AddMembersToConversationViewModel method addMembersToConversation() to add members to a conversation

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-767/2/) **failed**.

**Review by yamilmedina — APPROVED** [review]
Hey! I added small comments, but I'm pretty happy with the result here, the structure now looks more understandable and extensible. Great work as usual, Dr. ! 🙌

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-767/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-767/8/) **failed**.

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-767/9/) **failed**.

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-767/12/) **failed**.

**Comment by AndroidBob** [comment]
Build [14](https://10.10.124.134/job/wire-android-reloaded/job/PR-767/14/) **failed**.

**Comment by AndroidBob** [comment]
Build [16](https://10.10.124.134/job/wire-android-reloaded/job/PR-767/16/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3935699)(3935699)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3935699)(3935699)-dev-release.apk)

**Pull request merged**
