### PR TITLE
feat: initiate SSO login [AR-1160]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1160" title="AR-1160" target="_blank">SubtaskAR-1160</a>  SSO use case
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

SSO login only contained ui, logic was missing. It needs to be initialized and the sso code needs to be validated.

### Solutions

Implemented logic in LoginSSOViewModel - SSO login initiate use case with error handling and opening the browser.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Run `LoginSSOViewModelTest` or try in app by opening "login" and switching to "SSO Login" tab.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-516/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3098455)(3098455)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3098455)(3098455)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-516/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3106626)(3106626)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3106626)(3106626)-dev-release.apk)

**Review by mchenani — APPROVED** [review]
🚀

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-516/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3138514)(3138514)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3138514)(3138514)-dev-release.apk)

**Pull request merged**
