### PR TITLE
feat: minimize ongoing call epic

### PR DESCRIPTION
**Pull request by alexandreferris**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] contains a reference JIRA issue number like `SQPIT-764`
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

[AR-1348](https://wearezeta.atlassian.net/browse/AR-1348)

### Issues

Couldn't minimize ongoing call

### Causes (Optional)

No action was taken on collapse button

### Solutions

Add navigate back on collapse button and component view to return to ongoing call if there is any for only two screens:
- ConversationScreen
- HomeScreen

### Dependencies (Optional)

Needs releases with:

- [X] #847 
- [X] #848 

### Testing

Tests were done manually.

#### How to Test

- Open App
- receive/start a call
- click minimize button in ongoing call screen
- status bar should be green with `RETURN TO CALL`
- Click `RETURN TO CALL` should open the ongoing call.

### Notes (Optional)

There are two possible issues:
- System back button doesn't properly collapse the ongoing call screen
- Microphone wrong state when re-opening ongoing call screen

both will be handled in a separate ticket.

### Attachments (Optional)
Conversation Screen with RETURN TO CALL in Status Bar

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-850/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4126682)(4126682)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4126682)(4126682)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-850/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4132380)(4132380)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4132380)(4132380)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-850/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4132663)(4132663)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4132663)(4132663)-dev-release.apk)

**Review by ohassine — APPROVED** [review]
Let's go 🚀

**Pull request merged**
