### PR TITLE
feat: add full list of group participants screen [AR-1888]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1888" title="AR-1888" target="_blank">SubtaskAR-1888</a>   Show full members list screen
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

User should be able to see a list of all participants. Participants tab on details screen shows up to 4 first members, to see all the rest, there should be a button at the bottom to open full participants list.

### Solutions

Created screen which shows list of all participants, cleaned up code not to duplicate anything - created common viewmodel and use case to get limited or full list of participants.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Open details of a group conversation that has more than 4 participants._

### Attachments (Optional)

device-2022-07-01-094310 (1)

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-730/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-730/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3769651)(3769651)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3769651)(3769651)-dev-release.apk)

**Review by tmspzz — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-730/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3770431)(3770431)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3770431)(3770431)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-730/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3770521)(3770521)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3770521)(3770521)-dev-release.apk)

**Pull request merged**
