### PR TITLE
chore: disable guests option change for admins in certain circumstances [AR-1906]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1906" title="AR-1906" target="_blank">StoryAR-1906</a>  Guest on/off control in group not usable for admins in certain circumstances
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When the admin is a guest (not from the owner's team), then shouldn't be allowed to change the guests option of that group, because otherwise he would throw himself out if he sets guests to off.

### Solutions

Disable the switch in such situation and show the information explaining why this is so.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Make a guest an admin of a group created by the team and open the group details of this group from this guest admin account.

### Attachments (Optional)

Screenshot_20220811_094734

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-846/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4123758)(4123758)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4123758)(4123758)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-846/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4132620)(4132620)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4132620)(4132620)-dev-release.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-846/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4161505)(4161505)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4161505)(4161505)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-846/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4166855)(4166855)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4166855)(4166855)-dev-release.apk)

**Pull request merged**
