### PR TITLE
fix: wrong orientation when uploading avatar through camera

### PR DESCRIPTION
**Pull request by gongracr**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Avatar picture appeared rotated on the preview picker screen when taken from the camera. The reason was that the uploaded picture was only being resampled (fixed rotation and resized) only after confirming the upload. Now the resampling is done on the preview step already instead. 

#### How to Test

Navigate to user's profile, select Take photo option and upload a new image. Check the rotation is correct on the preview step

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-930/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-930/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4342699)(4342699)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4342699)(4342699)-dev-release.apk)

**Review by Garzas — APPROVED** [review]
LGTM 🚀

**Review by yamilmedina — APPROVED** [review]
Great, nice to see this small adjustment to the avatar/assets handling 🥇

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-930/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4348295)(4348295)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4348295)(4348295)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-930/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4348727)(4348727)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4348727)(4348727)-dev-release.apk)

**Pull request merged**
