### PR TITLE
fix: refactored way to resample avatar and images assets

### PR DESCRIPTION
**Pull request by gongracr**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues
After assets refactoring, image messages were not being resampled. 

### Solutions
I refactored a bit the flow for resampling avatars (small size) and asset messages (medium size) so that they use the same new util method called `Uri.resampleImageAndCopyToTempPath()`

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test
Update your avatar image with a new large image and check the final one uploaded is way smaller. Same with images in conversations.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-793/1/) **failed**.

**Review by yamilmedina — APPROVED** [review]
Great work compa! Final touches on assets 🙌  🤟

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-793/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3977826)(3977826)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3977826)(3977826)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-793/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3978945)(3978945)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3978945)(3978945)-dev-release.apk)

**Pull request merged**
