### PR TITLE
fix: fixed crash when sending/receiving svg images

### PR DESCRIPTION
**Pull request by gongracr**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Sharing SVG files as images was causing some app crashes. Because even though their mime type is "image/svg", our app can't interpret this format in order to render it inlined in the chat.

### Solutions

To add a utils method to whitelist only "jpeg", "jpg" and "png" as _valid_ image types. If we plan on support or display other image types, we will need to add this mime type to the list.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Just share an svg file as image !

### Attachments (Optional)

https://user-images.githubusercontent.com/2468164/174822903-fb01c145-cb37-4703-ab77-2e1f77632460.mov

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-688/2/) **failed**.

**Review by vitorhugods — APPROVED** [review]
Clean ✨

BaconIsGoodForMeGIF

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-688/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3685607)(3685607)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3685607)(3685607)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-688/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3685747)(3685747)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3685747)(3685747)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-688/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3686116)(3686116)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3686116)(3686116)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-688/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3686796)(3686796)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3686796)(3686796)-dev-release.apk)

**Pull request merged**
