### PR TITLE
fix: crash when removing member from group conversation [AR-2038]

### PR DESCRIPTION
**Pull request by gongracr**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

App was crashing with a NPE when trying to remove a member from a conversation because the `conversationId` was null as it was not being initialised on the `OtherUserProfileScreenViewModel.state`

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Just navigate to a group where you are an admin, then try to remove a group member from his user profile screen and see that the confirmation dialog appears and that it removes the member from the group.

----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-934/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4349948)(4349948)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4349948)(4349948)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
Great catch 🦅 🐅 !

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-934/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4350187)(4350187)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4350187)(4350187)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-934/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4350441)(4350441)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4350441)(4350441)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-934/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4350554)(4350554)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4350554)(4350554)-dev-release.apk)

**Pull request merged**
