### PR TITLE
feat: hide the protocol selection when MLS is disabled 

### PR DESCRIPTION
**Pull request by typfel**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Don't show the protocol selection when creating a new conversation if MLS is disabled.

### Dependencies

Needs releases with:

- [ ] https://github.com/wireapp/kalium/pull/757

#### How to Test

1. Enable MLS for your user in team settings
2. Tap create new conversation 
3. protocol selection is visible/hidden

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by ohassine — APPROVED** [review]
👌

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-830/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4098883)(4098883)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4098883)(4098883)-dev-release.apk)

**Review by mchenani — APPROVED** [review]
LGTM🚀

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-830/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4099303)(4099303)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4099303)(4099303)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-830/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4099414)(4099414)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4099414)(4099414)-dev-release.apk)

**Pull request merged**
