### PR TITLE
fix: laggy scrolling / collapsing search bars [AR-2160]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2160" title="AR-2160" target="_blank">BugAR-2160</a>  UI is laggy cause the app is downloading images on every scroll
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

"Search users" list is laggy when scrolling.

### Causes (Optional)

Because of the implementation of the collapsing search bar which recomposes when scrolling.

### Solutions

Adjust and use already implemented collapsing solution used first on the other user profile screen. Another issue also had to be addressed - search bar on home screen which is currently hidden but we will implement it eventually. To make it all work, both NavHosts from home and conversations are flattened and merged into one, bottom tabs bar is moved to the home screen to have only single Scaffold and remove nested ones, otherwise bottom bar would be scrolling along with the whole content and slide under the screen, the same with the FAB button.

#### How to Test

Open "Conversations", click on "New" FAB button and try to scroll the list.

### Attachments (Optional)

https://user-images.githubusercontent.com/30429749/186178006-831a7ccf-21c3-4bdb-a716-5428af74811d.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-888/2/) **failed**.

**Review by trOnk12 — APPROVED** [review]
all though I had other solution in mind, this one looks great let's go ! 🔥 🔥

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-888/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4236095)(4236095)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4236095)(4236095)-dev-release.apk)

**Review by MohamadJaara — APPROVED** [review]
LGTM

**Pull request merged**
